RUN_STRINGS = (
    "Kemana Anda pikir Anda akan pergi?",
    "Hah? apa? apakah mereka lolos?",
    "ZZzzZZzz... Hah? apa? oh... hanya mereka lagi, lupakan saja.",
    "Kembali kesini!",
    "Tidak terlalu cepat...",
    "Jangan lari-lari di ruangan! 😠",
    "Jangan tinggalkan aku sendiri bersama mereka!! 😧",
    "Anda lari, Anda mati.",
    "Lelucon pada Anda, saya ada di mana-mana 😏",
    "Anda akan menyesalinya...",
    "Anda juga bisa mencoba /kickme, saya dengar itu menyenangkan 😄",
    "Ganggulah orang lain, tidak ada yang peduli 😒",
    "Anda bisa lari, tetapi Anda tidak bisa bersembunyi.",
    "Apakah itu semua yang kamu punya?",
    "Saya di belakang Anda...",
    "Larilah sesuka kalian, Anda tidak dapat melarikan diri dari takdir",
    "Kita bisa melakukan ini dengan cara mudah, atau dengan cara yang sulit.",
    "Anda tidak mengerti, bukan?",
    "Ya, kamu sebaiknya lari!",
    "Tolong, ingatkan aku betapa aku peduli?",
    "Saya akan berlari lebih cepat jika saya adalah Anda.",
    "Itu pasti orang yang kita cari.",
    "Semoga peluang akan selalu menguntungkan Anda.",
    "Kata-kata terakhir yang terkenal.",
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi.",
    '"Oh, lihat aku! Aku sangat keren, aku bisa lari dari bot!" - orang ini',
    "Ya ya, cukup ketuk /kickme saja 😏",
    "Ini, ambil cincin ini dan pergi ke Mordor saat Anda berada di sana.",
    "Legenda mengatakan, mereka masih berlari...",
    "Tidak seperti Harry Potter, orang tuamu tidak bisa melindungimu dariku.",
    "Ketakutan menyebabkan kemarahan. Kemarahan menyebabkan kebencian. Kebencian menyebabkan penderitaan. "
    "Jika Anda terus berlari ketakutan, Anda mungkin menjadi Vader berikutnya.",
    "Darah hanya menyebabkan darah, dan kekerasan melahirkan kekerasan. Tidak lebih. Balas dendam hanyalah nama lain untuk pembunuhan."
    "Jika anda terus berlari dan mengganggu yang lain, maka saya akan membalaskan dendam untuk yang terganggu.",
    "Teruskan, tidak yakin kami ingin Anda di sini.",
    "Anda seorang penyi- Oh. Tunggu. Kamu bukan Harry, lanjutkan berlari.",
    "DILARANG BERLARI DI KORIDOR! 😠",
    "Vale, deliciae.",
    "Siapa yang membiarkan anjing-anjing itu keluar?",
    "Itu lucu, karena tidak ada yang peduli.",
    "Ah, sayang sekali. Saya suka yang itu.",
    "Terus terang, aku tidak peduli.",
    "Saya tidak peduli dengan anda... Jadi, lari lebih cepat!",
    "Anda tidak bisa MENANGANI kebenaran!",
    "Dulu, di galaksi yang sangat jauh... Seseorang pasti peduli dengan dia.",
    "Hei, lihat mereka! Mereka berlari dari Emilia yang tak terelakkan ... Lucu sekali 😂",
    "Han menembak lebih dulu. Begitu juga saya.",
    "Apa yang kamu kejar? kelinci putih?",
    "Sepertinya dokter akan mengatakan... LARI!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_SAITAMA_TEMPLATES = (
    "Tampar aku sekali lagi dan aku akan membungkammu.",
    "Berhenti menamparku. REEEEEEEEEEEEEE.",
    [
        "Saya membungkam Anda sebentar.",  # balasan normal
        "Berhenti menamparku hanya karena aku tidak bisa membungkammu. REEEEEEEEEE.",  # balas admin
        "diam",  # memerintah
        "Diam!",
        "Kesunyian!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} dibunuh oleh sihir.",
    "{user2} kelaparan tanpa tepukan.",
    "{user2} terlempar ke dalam kehampaan oleh {user1}.",
    "{user2} pingsan.",
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} diputihkan!.",
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} pingsan!.",
    "{user2} punya rekt.",
    "{user2} melon dibelah oleh {user1}.",
    "{user2} diiris dan dipotong dadu oleh {user1}.",
    "{user2} bermain kentang panas dengan granat.",
    "{user2} ditusuk oleh {user1}.",
    "{user2} makan granat.",
    "{user2} apa untuk makan malam?!",
    "{user2} diakhiri oleh {user1}.",
    "{user1} di-spam {user2} email.",
    "{user1} Terenkripsi RSA {user2} dan menghapus kunci pribadi.",
    "{user1} taruh {user2} di zona pertemanan.",
    "{user1} tamparan {user2} dengan permintaan penghapusan DMCA!",
    "{user2} mendapat telepon rumah dari Dokter {user1}.",
    "{user1} dipenggal {user2}.",
    "{user2} dilempari batu...oleh massa yang marah.",
    "{user1} menggugat celana {user2}.",
    "{user2} adalah satu pukulan KO oleh {user1}.",
    "{user1} terkirim {user2} ke dalam lubang memori.",
    "{user2} adalah sebuah kesalahan. - '{user1}' ",
    "{user2} dibuat berlebihan.",
    "{user1} {hits} {user2} dengan kelelawar!.",
    "{user1} {hits} {user2} dengan Tendangan Taijutsu!.",
    "{user1} {hits} {user2} dengan X-Gloves!.",
    "{user1} {hits} {user2} dengan Pukulan Jet!.",
    "{user1} {hits} {user2} dengan Jet Pistol!.",
    "{user1} {hits} {user2} dengan Amerika Serikat Smash!.",
    "{user1} {hits} {user2} dengan Detroit Smash!.",
    "{user1} {hits} {user2} dengan Texas Smash!.",
    "{user1} {hits} {user2} dengan California Smash!.",
    "{user1} {hits} {user2} dengan New Hampshire Smash!.",
    "{user1} {hits} {user2} dengan Pukulan Missouri!.",
    "{user1} {hits} {user2} dengan Smash Carolina!.",
    "{user1} {hits} {user2} dengan King Kong Gun!.",
    "{user1} {hits} {user2} dengan tongkat baseball - yang terbuat dari logam.!.",
    "*Pukulan serius {user2}*.",
    "*Pukulan biasa {user2}*.",
    "*Pukulan Normal Berturut-turut {user2}*.",
    "*Pukulan Normal Dua Tangan Berturut-turut {user2}*.",
    "*mengabaikan {user2} untuk membiarkan mereka mati karena malu*.",
    "*poin di {user2}* Ada apa dengan lancang... anak hilang ini?.",
    "*Hits {user2} dengan Tornado Api*.",
    "{user1} menusuk {user2} in the eye !",
    "{user1} menusuk {user2} on the sides!",
    "{user1} menusuk {user2}!",
    "{user1} menusuk {user2} dengan jarum!",
    "{user1} menusuk {user2} dengan pena!",
    "{user1} menusuk {user2} dengan pistol setrum!",
    "{user2} diam-diam adalah Furry!",
    "Hei Semuanya! {user1} meminta saya untuk menjadi jahat!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Ambil ini {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Di Sini {user2} pegang ini\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Semprotan serangga {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} kamu hama!",
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} dengan {item}.",
    "{user1} {hits} {user2} di wajah dengan {item}.",
    "{user1} {hits} {user2} sekitar sedikit dengan {item}.",
    "{user1} {throws} Sebuah {item} pada {user2}.",
    "{user1} meraih {item} dan {throws} itu di {user2}wajah.",
    "{user1} meluncurkan sebuah {item} di dalam {user2}arah umum.",
    "{user1} mulai menampar {user2} konyol dengan {item}.",
    "{user1} pin {user2} ke bawah dan berulang kali {hits} mereka dengan {item}.",
    "{user1} meraih {item} dan {hits} {user2} dengan itu.",
    "{user1} dasi {user2} ke kursi dan {throws} Sebuah {item} pada mereka.",
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lava.",
    "{user1} diganggu {user2}.",
    "Nyaan makan {user2}kaki. *nomnomnom*",
    "{user1} {throws} bola master di {user2}, resistensi adalah sia-sia.",
    "{user1} hits {user2} with balok aksi...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda {user2}.",
    "{user2} diubah menjadi referensi Jojo!",
    "{user1} hits {user2} dengan {item}.",
    "Putaran 2!..Siap? .. FIGHT!!",
    "WhoPixel akan oof {user2} menuju tak terbatas dan melampauinya.",
    "{user2} makan kelelawar dan menemukan penyakit baru.",
    "{user1} dilipat {user2} menjadi pesawat kertas",
    "{user1} melayani {user2} beberapa sup kelelawar.",
    "{user2} dikirim ke rumah mereka, planet kera.",
    "{user1} ditendang {user2} keluar dari kereta yang bergerak.",
    "{user2} baru saja membunuh anjing John Wick.",
    "{user1} melakukan mantra Avada Kedavra pada {user2}.",
    "{user1} dikenakan {user2} ke tungku yang menyala-nyala.",
    "Sakura Haruno menjadi lebih berguna daripada {user2}",
    "{user1} dicabut {user2}penopang hidup.",
    "{user1} berlangganan {user2}' hingga 5 tahun internet buruk.",
    "Anda tahu apa yang lebih buruk dari lelucon Ayah? {user2}!",
    "{user1} mengambil semua {user2}kue kering.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} kehilangan bagian ras mereka!",  # Tidak ada permainan tidak ada referensi kehidupan
    "Diam {user2}, kamu hanya {user2}.",  # Tidak ada permainan tidak ada referensi kehidupan
    "{user1} hits {user2} dengan Aka si anse!",  # Tidak ada permainan tidak ada referensi kehidupan
    "@NeoTheKitty goresan {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Pembunuh goblin membunuh {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} tepukan {user2} di atas kepala.",
    "*gosok dengan lembut {user2}kepala*.",
    "*{user1} mofumofus {user2}kepala*",
    "*{user1} berantakan {user2}kepala*",
    "*{user1} menggosok dengan kuat {user2}kepala*",
    "*{user2}waifu menepuk kepala mereka*",
    "*{user2}mendapat tepuk kepala gratis*",
    "Tidak ada tepukan untuk {user2}!",
    "Oh tidak! Kita semua kehabisan tepukan.",
    "Ini adalah zona larangan tepuk yang ditunjuk!",
    "Tidak ada tepukan untuk {user2}!",
    "{user1} rampasan {user2} dengan tepuk kepala!",
    "{user2} menerima satu headpat gratis!",
    "{user1} tepuk kepala {user2} sambil memberikan bantal pangkuan",
    "{user1} tepukan agresif {user2}",
    "{user1} dengan lembut membelai {user2}kepala",
    "Pat, pat, pat, pat",
    "{user2} tidak bisa melarikan diri {user1}tepuk kepala",
    "{user2}.exe telah berhenti bekerja",
    "{user1} menggosok {user2} di leher",
    "Harus... memeras... PAKAIAN KEPALA",
    "{user1} tepuk kepala {user2}kepala dengan tepukan",
    "{user1} tepukan {user2} tiba-tiba",
    "{user1} tepukan {user2} dengan persetujuan, mungkin?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} tepuk kepala {user2} pukul 420pm",
    "{user1} gosok perut {user2}",
    "{user1} tepukan {user2} ramah",
    "{user2} menggunakan PAKAIAN KEPALA? O KAWAII KOTO",
    "*headpats.gif mengintensifkan untuk {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "wajan besi cor",
    "ikan tongkol",
    "tongkat pemukul baseball",
    "pedang excalibur",
    "tongkat kayu",
    "paku",
    "mesin pencetak",
    "sekop",
    "monitor CRT",
    "buku pelajaran fisika",
    "pemanggang roti",
    "potret Richard Stallman",
    "televisi",
    "lima ton truk",
    "gulungan lakban",
    "buku",
    "laptop",
    "televisi lama",
    "karung batu",
    "ikan lele",
    "gas LPG",
    "tongkat pemukul berduri",
    "pemadam api",
    "batu yang berat",
    "potongan kotoran",
    "sarang lebah",
    "sepotong daging busuk",
    "beruang",
    "sekarung batu bata",
)

THROW = (
    "melempar",
    "teman kencan",
    "cekik",
    "melempar",
)

HIT = (
    "memukul",
    "memukul",
    "menampar",
    "memukul",
    "menampar keras",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("kepala", "ekor")

EIGHTBALL = [
    "🟢 Seperti yang saya lihat, ya.",
    "🟡 Tanya lagi nanti.",
    "🟡 Lebih baik tidak memberitahumu sekarang.",
    "🟡 Tidak dapat memprediksi sekarang.",
    "🟡 Berkonsentrasilah dan tanyakan lagi.",
    "🟡 Jangan mengandalkannya.",
    "🟢 Itu pasti.",
    "🟢 Memang begitu.",
    "🟢 Kemungkinan besar.",
    "🔴 Jawaban saya adalah tidak.",
    "🔴 Sumber saya mengatakan tidak.",
    "🔴 Outlook tidak begitu bagus.",
    "🟢 Tampilan bagus.",
    "🟡 Balas kabur, coba lagi.",
    "🟢 Tanda menunjukkan ya.",
    "🔴 Sangat meragukan.",
    "🟢 Tanpa keraguan.",
    "🟢 Ya.",
    "🟢 Ya – pasti.",
    "🟢 Anda dapat mengandalkannya.",
]

DECIDE = ("Ya.", "Tidak.", "Mungkin.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "(ﾉ≧∇≦)ﾉ ﾐ ┻━┻",
    "Saya kehabisan meja, akan memesan lebih banyak.",
    "Lakukan beberapa pekerjaan alih-alih meja flippin.",
)
