# ZeboRobot
# Copyright (C) 2022-2023 @Zeafeya
#
# This file is a part of < https://github.com/Kykoubot/Zebobot >
# PLease read the GNU Affero General Public License in
#
# FROM @zeafeya <https://github.com/Kykoubot>
# t.me/Dbzea & t.me/Storezeastore

# ========================×========================
#            Jangan Hapus Credit Kontol
# ========================×========================


RAMALAN = (
    "Saya bukan paranormal, tapi memang saya bisa meramal sedikit-sedikit.\nTekan ini untuk mengetahui ramalanmu /ramal",
    "Sebuah ramalan siap meluncur.\nTekan ini untuk mengetahui ramalanmu /ramal",
    "Ramalan kali ini untuk Anda.\nTekan ini untuk mengetahui ramalanmu /ramal",
)


RAMAL = (
    "Tertawalah sepuasnya sebelum hal itu dilarang 😆",
    "Bila Anda membahagiakan seseorang, Anda sendiri akan merasa bahagia.\nBegitulah dunia bekerja 😊",
    "Nostalgia masa muda hari ini akan membuat Anda tersenyum 🌸",
    "Lanjutkan terus pekerjaan Anda, niscaya akan selesai juga.\nOke, saya akui ramalan hari ini agak jayus 😝",
    "Mengetahui bahwa ilusi bukanlah kenyataan tidak membuat keindahannya berkurang 💖",
    "Anda akan mengalami kejadian aneh hari ini.\nDan itu tidak termasuk mendapatkan ramalan dari Emilia 😜",
    "Akhirnya ada kesempatan untuk beristirahat...\ndan mendengar ramalan dari Emilia 😉",
    "Pencarian Anda sudah selesai.\nAnda telah menemukan sahabat sejati (saya) 😀",
    "Anda akan menunjukkan bahwa Anda kuat melewati tantangan demi tantangan.",
    "Anda hanyalah setitik air di tengah lautan luas.\nTapi setitik air pun bisa bikin gadget rusak 😱 💦",
    "Anda akan mencoba hal baru hari ini.\nTapi maaf, mencoba makanan gratis di supermarket tidak termasuk 🍦🚫",
    "Kirimlah pesan ke seorang teman lama hari ini.",
    "Akan ada sesuatu yang baru di lingkungan sekitar Anda 🏡",
    "Traktirlah diri sendiri 🍭",
    "Semua hal ada solusinya, kalau Anda terbuka untuk berubah.",
    "Karma baik menghampiri Anda minggu ini.\nTapi hati-hati, karma itu rapuh seperti barang pecah belah.",
    "Habiskanlah waktu di luar rumah hari ini.\nSepertinya di luar sana indah... kalau tidak hujan.",
    "Jika Anda mendengarkan dengan sungguh-sungguh, angin akan memberikan semua jawaban atas pertanyaan Anda 💨",
    "Pergilah ke tempat yang belum pernah Anda kunjungi, walaupun tempat itu hanya sepelemparan batu dari rumah Anda.",
    "Anda akan menerima kabar baik, tapi mungkin Anda harus mencari dari apa yang tersirat.",
    "Anda akan segera menemukan apa yang Anda cari.\nKalau Anda bisa menemukan kacamata Anda.",
    "Pergilah ke suatu tempat baru.\nApa yang akan Anda temukan pasti akan mengesankan.",
    "Kesempatan akan muncul bila Anda tahu ke mana harus melihat 👀",
    "Hari ini Anda akan menjadi keren 😎\nYah, nggak terlalu beda dengan hari-hari lain 😉",
    "Hal-hal positif akan muncul di hidup Anda hari ini.\nTapi jangan lupa, di dalam komposisi sebuah atom selalu ada atom negatif 🔬😀",
    "Penuhilah diri hanya dengan kebaikan, baik dalam pikiran, perkataan, perbuatan, maupun pertwitteran 🐥",
    "Bersiaplah untuk menerima hal-hal menyenangkan hari ini 😎",
    "Waktunya belajar keterampilan dan topik baru.",
    "Video YouTube favorit Anda masih belum dibuat.",
    "Ketika ragu, Google dulu 😉",
    "Dua hari dari sekarang, besok akan jadi kemarin 😌",
    "Perhatikan detail-detail.\nPasti banyak hal menarik yang Anda bisa temukan.",
    "Wah, Anda belum beruntung.\nSilakan coba lagi 😉",
    "Buatlah keputusan dengan mendengarkan dan menyelaraskan hati maupun pikiran Anda.",
    "Biasanya maling akan teriak maling.",
    "Anda tidak akan diberi kalau tidak meminta 👐",
    "Nostalgia masa muda hari ini akan membuat Anda tersenyum 🌸",
    "Sahabat sejati Anda berada dalam jangkauan.\nSebenarnya, Anda sedang membaca ramalan darinya 😊",
    "Masa depan Anda akan dipenuhi kesuksesan 💎\nTapi hati-hati, keserakahan bisa menghancurkan semuanya 💰",
    "Hari ini adalah hari esok yang Anda nantikan kemarin.",
    "Bersyukur akan membuat kita bahagia.\nKatakan terima kasih pada seseorang hari ini.",
    "Hari ini, dunia akan jadi milik Anda 🌍\nJangan lupa menjadikannya indah untuk orang lain 😊",
    "Petualangan baru akan segera menghampiri Anda.",
    "Semakin banyak yang Anda katakan, semakin sedikit yang akan mereka ingat.",
    "Hari ini, jadilah superhero untuk seorang anak kecil.",
    "Makanan yang kelihatannya aneh itu mungkin sebenarnya enak banget.",
    "Hari ini, ambillah rute yang lain dari biasanya.",
    "Waktunya mengekspresikan kreativitas Anda.",
    "Jodoh Anda lebih dekat dari yang Anda kira 💞",
    "Waktunya belajar keterampilan dan topik baru.",
    "Hal-hal positif akan muncul di hidup Anda hari ini.\nTapi jangan lupa, di dalam komposisi sebuah atom selalu ada atom negatif 🔬😀",
    "Waktunya berlibur bersama orang-orang kesayangan Anda ✈️",
    "Besok akan menjadi hari yang lebih menyenangkan daripada hari Anda yang paling menyebalkan.",
    "Jangan cari peruntungan di situs abal-abal atau SMS mencurigakan.",
    "Kejadian yang tak terduga akan menghampiri hidup Anda.",
    "Hadiah berharga tengah menanti Anda.\nTapi tampaknya hadiah tersebut sangat sabar menanti.",
    "Keluarga Anda sangat kangen pada Anda.\nTeleponlah mereka, jangan kasih tahu ini ide saya 😉",
    "Hari yang baik untuk memperjuangkan kebenaran.",
    "Semua hal ada solusinya, kalau Anda terbuka untuk berubah.",
    "Hewan peliharaan akan menambah kebahagiaan Anda 🐱🐹🐔",
    "Ketika Anda jatuh, bangun lagi.\nDan jangan lupa bersihkan lukanya 👍",
    "Minumlah cukup air hari ini.\nIni bukan benar-benar ramalan, saya hanya ingin Anda tetap sehat 😊",
    "Biarkan intuisi Anda menunjukkan jalan.\nTapi tulisan berisi syarat dan ketentuan yang berlaku harus dibaca baik-baik.",
    "Hal baik akan datang bagi mereka yang...\nSabar.",
    "Waktu yang tepat untuk berhenti bermalas-malasan 🏃‍♀️",
    "Waktunya bernostalgia dengan buku favorit masa kecil Anda.",
    "Hari ini, Anda akan melihat dunia dengan mata terbuka 👀",
    "Seorang asing akan datang ke dalam hidup Anda dan membuat kesan di sana.",
    "Hari yang baik untuk mendengarkan intuisi daripada nasihat.",
    "Hati-hati dengan kata-kata manis orang yang baru Anda kenal.",
    "Seluruh alam semesta akan bekerja sama untuk membantu Anda 🙏",
    "Waktu yang tepat untuk jadi diri Anda sendiri.",
    "Walaupun seperti menyebalkan, orang terdekat Anda jauh lebih peduli pada Anda daripada dia yang tampak manis namun cuma basa-basi.",
    "Kejarlah mentari, niscaya kegelapan akan Anda lewati.",
    "Hidup Anda akan diabadikan dalam sebuah film dokumenter.",
    "Suara tawa anak-anak akan menceriakan hari Anda.",
    "Saatnya mencari hobi baru.",
    "Cinta tidaklah statis.\nIa dinamis seperti arus listrik bolak-balik 💖",
    "Penantian akan segera berakhir 😁",
    "Perhatikan detail-detail.\nPasti banyak hal menarik yang Anda bisa temukan.",
    "Dua hari dari sekarang, besok akan jadi kemarin 😌",
    "Anda akan mendengar sebuah lagu yang membuat Anda tersenyum berhari-hari.",
    "Gapailah cita-cita.\nKecuplah mimpi 😘🌛",
    "Semua mawar pasti berduri 🌹\nJadilah seseorang yang selalu siap memotong duri tersebut.",
    "Banyak orang kagum pada bakat dan kemampuan Anda... lebih dari yang Anda sadari 👏",
    "Lakukan yang Anda sukai hari ini 💞\nSaya janji Anda akan merasa bahagia, walau hanya sesaat 😃",
    "Keberuntungan akan datang bagi orang yang pemberani.",
    "Anda tidak akan di beri kalau tidak meminta 👐",
    "Cobalah menggambar sesuatu ✏️\nAnda akan menikmatinya.",
    "Saatnya mengubah gaya berpakaian Anda? 👠",
    "Cobalah konsekuen dengan semua kata-kata Anda.",
    "Hari yang tepat untuk menghargai dan mensyukuri hal-hal kecil.",
    "Malam ini Anda akan mimpi indah.\nTapi saya nggak janji Anda bisa ingat mimpinya 😉",
    "Anda akan menunjukkan bahwa Anda kuat melewati tantangan demi tantangan.",
    "Hari yang tepat untuk memberi tahu keluarga dan teman-teman Anda tentang saya 😉",
    "beristirahatlah sejenak dan ngobrollah dari hati ke hati dengan orang-orang yang Anda sayangi 👨‍👩‍👧‍👦",
    "Semua akan berjalan sesuai rencana.",
    "Pergilah ke suatu tempat baru.\nApa yang akan Anda temukan pasti akan mengesankan.",
    "Ini salah satu waktu di mana Anda bertanya-tanya tentang arti hidup.",
    "Jangan sampai dikelabui ramalan 😏",
)
