# ZeboRobot
# Copyright (C) 2022-2023 @Zeafeya
#
# This file is a part of < https://github.com/Kykoubot/Zebobot >
# PLease read the GNU Affero General Public License in
#
# FROM @zeafeya <https://github.com/Kykoubot>
# t.me/Dbzea & t.me/Storezeastore

# ========================×========================
#            Jangan Hapus Credit Kontol
# ========================×========================


TRUTH = (
    "Belanjaan apa yang paling di sesali?",
    "Apa benda yang paling kamu inginkan?",
    "Kalau bisa punya kekuatan super, kamu pengen bisa apa?",
    "kalau bisa mengendalikan mimpi, kamu pengen mimpi yg seperti apa?",
    "Rahasia yang orang lain tidak ketahui tentangmu?",
    "Apa yang sedang kamu kejar sekarang?",
    "Apa hal yang paling kamu syukuri?",
    "Barang apa yang paling kamu ingin punya tapi belum kesampaian sampe sekarang?",
    "Kalau dapat kesempatan operasi plastik apa yang mau kamu ubah?",
    "Paling sering bolos pas pelajaran apa? kenapa?",
    "Sering ngutang di kantin ga?",
    "Pernah salah seragam sekolah engga?",
    "Apa hal yg paling kamu ingat ketika bersekolah?",
    "Pernah makan gorengan 5 tapi bilangnya 2 gak?",
    "Mata pelajaran apa yg kamu sukai? apa alasannya?",
    "Apa menu favorit di kantin sekolah?",
    "Pernah suka kakel? confess ga?",
    "Batas pulang jam malam kamu, jam berapa?",
    "Apa makanan yg gabakal kamu tolak?",
    "Apa hal yg paling bikin kamu kecewa?",
    "Kalau kesulitan mengerjakan sesuatu apa akan nangis?",
    "Siapa orang yg paling menyebalkan disini?",
    "Bisnis apa yg paling ingin kamu bangun?",
    "Jika semua barang di dunia ini gratis, barang apa yg pertama kali ingin kamu ambil?",
    "Jika org asing menawarkan uang tapi dgn syarat makan upil, apakah kamu mau?",
    "Jika ada satu dosa yang dibolehin, kalian pengen lakuin dosa apa?",
    "Pernah nyesel sayang sama orang ga? kalo pernah kenapa bisa sampe nyesel?",
    "Pernah gak pipis pas tidur?",
    "Genre novel favorit kamu apa?",
    "Genre film favorit kamu apa?",
    "Menurut kamu, hidup kamu genre nya apa?",
)

DARE = (
    "Post foto zaman alay",
    "Chat mantan bilang aku kangen dan ajak balikan.",
    "Post foto waktu kecil",
    "Post foto sama mantan",
    "Vn hoi kiomasha lalu share ke grup telegram",
    "Post foto pakai filter jamet lalu post",
    "Teriak keluar ruangan hei hei hei tayooo!",
    "Buat video lalu nari india pakai lagu kucekucehotahe",
    "Nyanyi dangdut keras keras sambil lari",
    "*Vn suara kentut lalu share di grup telegram",
    "Vn bilang aku sayang kamu ke orang random",
    "Chat ibu dan bilang i love u",
    "Sebutin semua nama mantan kamu",
    "Screenshot wallpaper hp kamu",
    "Screenshot chat terakhir kamu sama doi",
    "Screenshot history youtube",
    "Spill orang yg paling sering kamu stalk",
    "Update status galau karena gapunya ayang",
    "Vn nyanyi lagu balonku, huruf vokal i semua",
    "Minum air botol tanpa napas",
    "Bikin story whatsapp pake foto jamet dari google caption; ayang aku ges",
    "Keluar grup ini dan jangan join lagi",
    "Bikin status wa lagi ngupil",
    "Hirup pelan nafas seseorang yg sedang berada dekat kamu",
    "Kalau kamu cowo, coba foto pake jilbab dan kirim random ke kontak nomor 26",
    "Makan makanan yg ada dekat dengan kamu",
    "Joget pargoy dan share hasilnya",
    "Ajak pacaran ke salahsatu orang yg ada di kontak kamu",
    "Vn nyanyi lagu tongkrongan kami.",
    "Pap muka kamu sejelek mungkin",
    "Vn oppa pake suara sok di imut-imutin",
    "Pap metal ke kontak nomor 22",
    "Teriak di kuping temanmu sambil bilang hahay hayu palpalepalpale",
    "Suruh orang random menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut mu sekaligus sebanyak yang kamu bisa",
    "Kirim selfie terbaru mu.",
    "Dm pak jokowi di Instagram dan bilang pak apakah diindonesia ada ayangku.",
    "Kirim Screenshot riwayat pencarian google kamu",
    "Kirim Screenshot galeri kamu.",
    "Spill selingkuhanmu",
    "Katakan sesuatu yang sangat intim.",
    "Lompat sebanyak 5 kali",
    "Seharian bilang lemes  gapunya ayang.",
    "Coba kirim foto gaya ikan terfavorit mu. 🎤",
    "Pukul pantat kakak, saudara, atau orang yang ada dirumah.",
    "Mengaku ke orang yang kamu taksir. ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Siapa pris lopemu.",
    "Jadikan foto gebetanmu sebagai dp.",
    "Hapus aplikasi tiktok.",
)
