# ZeboRobot
# Copyright (C) 2022-2023 @Zeafeya
#
# This file is a part of < https://github.com/Kykoubot/Zebobot >
# PLease read the GNU Affero General Public License in
#
# FROM @zeafeya <https://github.com/Kykoubot>
# t.me/Dbzea & t.me/Storezeastore

# ========================×========================
#            Jangan Hapus Credit Kontol
# ========================×========================


TRUTH = (
    "Acara tv apa yang paling tidak kamu sukai?, Beritahu alasannya!",
    "Apa hal yang membuatmu senang, tetapi orang tua kamu tidak mengetahuinya?",
    "Pernahkah kamu selingkuh? Jika pernah, apa alasannya kamu selingkuh?",
    "Apa hal terburuk yg pernah kamu lakukan?",
    "Apa yang kamu lakukan selama bulan ini?",
    "Apa fantasi terbesar atau teranehmu?",
    "Apakah kamu pernah mencintai dua orang dalam waktu bersamaan?",
    "Apakah kamu punya bakat terpendam? Apa itu?",
    "Apakah kamu pernah melanggar hukum? Hukum apa yang kamu langgar?",
    "Siapa selebriti crush mu?",
    "Kebohongan terbesar apa yang pernah kamu lakukan?",
    "Apa penyesalan terburukmu?",
    "Apa hal paling memalukan yang pernah kamu lakukan?",
    "Kenapa kamu putus sama mantan?",
    "Apa hal yang paling membuatku merasa insecure?",
    "Apa kebohongan terparah yang pernah kamu lakukan ke orang tua?",
    "Apakah kamu pernah jatuh cinta kepada sahabatmu sendiri?",
    "Berapa jumlah mantan kamu? Coba list!",
    "Hal terburuk apa yang pernah dilakukan orang terhadap mu?",
    "Hal apa yang paling bisa membuatmu menangis?",
    "Berapa uang jajan kamu dalam sebulan?",
    "Barang apa yang paling penting untuk hidupmu?",
    "Kapan pertama kali kamu pacaran?",
    "Siapa yang paling kamu sukai disini?",
    "Hal apa yang paling menjijikan yang pernah kamu lakukan?",
    "Hal apa yang paling kamu syukuri dalam hidup?",
    "Apa yang membuat kamu gamon sama mantan?",
    "Barang apa saja yang di berikan mantan kamu?",
    "Apa hal yang paling memalukan yang pernah kamu lakukan ketika bersama doi?",
    "Apa pendapatmu tentang perselingkuhan?",
    "Kapan terakhir kali kamu menangis?",
    "Kapan terakhir kali kamu kentut?",
    "Apa ketakutan terbesarmu?",
)

DARE = (
    "Lakukan rap gaya bebas selama 3 menit, tanpa nafas.",
    "Biarkan orang lain membuat status menggunakan akun sosial mediamu.",
    "Cium salah satu kaos kaki yang ada dirumah, lalu pap ke grup.",
    "Makan satu gigitan kulit pisang dan oncam di obrolan video/obrolan suara.",
    "Tirukan suara salah satu penyanyi sampai ada yang bisa menebak.",
    "Ungkapkan perasaanmu kepada gebetanmu.",
    "",
    "Buat video lalu nari india pakai lagu kucekucehotahe",
    "Nyanyi dangdut keras keras sambil lari",
    "*Vn suara kentut lalu share di grup telegram",
    "Vn bilang aku sayang kamu ke orang random",
    "Chat ibu dan bilang i love u",
    "Sebutin semua nama mantan kamu",
    "Screenshot wallpaper hp kamu",
    "Screenshot chat terakhir kamu sama doi",
    "Screenshot history youtube",
    "Spill orang yg paling sering kamu stalk",
    "Update status galau karena gapunya ayang",
    "Vn nyanyi lagu balonku, huruf vokal i semua",
    "Minum air botol tanpa napas",
    "Bikin story whatsapp pake foto jamet dari google caption; ayang aku ges",
    "Keluar grup ini dan jangan join lagi",
    "Bikin status wa lagi ngupil",
    "Hirup pelan nafas seseorang yg sedang berada dekat kamu",
    "Kalau kamu cowo, coba foto pake jilbab dan kirim random ke kontak nomor 26",
    "Makan makanan yg ada dekat dengan kamu",
    "Joget pargoy dan share hasilnya",
    "Ajak pacaran ke salahsatu orang yg ada di kontak kamu",
    "Vn nyanyi lagu tongkrongan kami.",
    "Pap muka kamu sejelek mungkin",
    "Vn oppa pake suara sok di imut-imutin",
    "Pap metal ke kontak nomor 22",
    "Teriak di kuping temanmu sambil bilang hahay hayu palpalepalpale",
    "Suruh orang random menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut mu sekaligus sebanyak yang kamu bisa",
    "Kirim selfie terbaru mu.",
    "Dm pak jokowi di Instagram dan bilang pak apakah diindonesia ada ayangku.",
    "Kirim Screenshot riwayat pencarian google kamu",
    "Kirim Screenshot galeri kamu.",
    "Spill selingkuhanmu",
    "Katakan sesuatu yang sangat intim.",
    "Lompat sebanyak 5 kali",
    "Seharian bilang lemes  gapunya ayang.",
    "Coba kirim foto gaya ikan terfavorit mu. 🎤",
    "Pukul pantat kakak, saudara, atau orang yang ada dirumah.",
    "Mengaku ke orang yang kamu taksir. ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Siapa pris lopemu.",
    "Jadikan foto gebetanmu sebagai dp.",
    "Hapus aplikasi tiktok.",
)
